flowchart LR
    AA["AA: 0"]
    BB["BB: 13"] 
    CC["CC: 2"]
    DD["DD: 20"] 
    EE["EE: 3"] 
    FF["FF: 0"] 
    GG["GG: 0"] 
    HH["HH: 22"]
    II["II: 0"] 
    JJ["JJ: 21"]

    AA <--> DD
    AA <--> II
    AA <--> BB
    BB <--> CC
    CC <--> DD
    DD <--> EE
    EE <--> FF
    FF <--> GG
    GG <--> HH
    II <--> JJ