%%{init: {"flowchart": {"defaultRenderer": "elk"}} }%%
flowchart TD
	classDef path fill:#f00;
	AA[AA: 0]:::path
	AP[AP: 0]
	AU[AU: 20]
	BC[BC: 0]
	BT[BT: 0]
	CW[CW: 0]
	CX[CX: 13]
	DK[DK: 0]
	EB[EB: 0]
	FR[FR: 0]
	GP[GP: 0]
	GY[GY: 9]
	HS[HS: 8]
	HW[HW: 0]
	IG[IG: 0]
	IM[IM: 0]
	IZ[IZ: 0]
	JH[JH: 0]
	JN[JN: 0]
	JQ[JQ: 0]
	JY[JY: 0]
	KI[KI: 0]
	KR[KR: 17]
	LI[LI: 25]
	LW[LW: 0]
	MF[MF: 15]
	MV[MV: 14]
	NG[NG: 21]
	NX[NX: 0]
	OH[OH: 0]
	OI[OI: 5]
	OX[OX: 0]
	PJ[PJ: 0]
	PM[PM: 0]
	QK[QK: 0]
	QM[QM: 0]
	QS[QS: 0]
	RJ[RJ: 0]
	SI[SI: 0]
	SU[SU: 0]
	TF[TF: 0]
	TL[TL: 0]
	TT[TT: 0]
	UC[UC: 0]
	UY[UY: 0]
	VK[VK: 0]
	WA[WA: 0]
	WE[WE: 0]
	WH[WH: 0]
	WJ[WJ: 0]
	WW[WW: 6]
	WX[WX: 16]
	XK[XK: 0]
	XS[XS: 4]
	XU[XU: 3]
	YJ[YJ: 0]
	YL[YL: 0]
	YS[YS: 0]
	ZL[ZL: 0]
	ZO[ZO: 0]
	ZY[ZY: 10]

	AA <--> HW
	AA <--> JH
	AA <--> TF
	AA <--> WJ
	AA <--> FR
	AP <--> GY
	AP <--> JY
	AU <--> BT
	AU <--> QK
	AU <--> VK
	BC <--> CX
	BC <--> ZY
	BT <--> WA
	CW <--> XS
	CW <--> XU
	CX <--> OH
	CX <--> QM
	DK <--> IZ
	DK <--> OI
	EB <--> XU
	EB <--> YL
	FR <--> XS
	GP <--> GY
	GP <--> HW
	GY <--> YL
	GY <--> ZO
	HS <--> IM
	HS <--> UC
	HS <--> UY
	HS <--> WJ
	HS <--> XK
	IG <--> WX
	IG <--> ZY
	IM <--> WH
	IZ <--> XS
	JH <--> OI
	JN <--> JQ
	JN <--> XS
	JQ <--> KR
	JY <--> KR
	KI <--> KR
	KI <--> NX
	KR <--> WA
	LI <--> SI
	LI <--> YS
	LW <--> OI
	LW <--> TT
	MF <--> QS
	MF <--> RJ
	MV <--> QK
	MV <--> TT
	MV <--> WH
	MV <--> ZL
	NG <--> NX
	OH <--> WX
	OI <--> OX
	OI <--> SU
	OX <--> UY
	PJ <--> UC
	PJ <--> WW
	PM <--> RJ
	PM <--> ZY
	QM <--> ZO
	QS <--> WW
	SI <--> VK
	SU <--> XU
	TF <--> TL
	TL <--> XU
	WE <--> GY
	XK <--> YJ
	XS <--> WE
	YJ <--> XU
	YS <--> ZL