// Code generated by "stringer -type=Pulse"; DO NOT EDIT.

package exercises

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Low-0]
	_ = x[High-1]
}

const _Pulse_name = "LowHigh"

var _Pulse_index = [...]uint8{0, 3, 7}

func (i Pulse) String() string {
	if i < 0 || i >= Pulse(len(_Pulse_index)-1) {
		return "Pulse(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Pulse_name[_Pulse_index[i]:_Pulse_index[i+1]]
}
